i[directory]
truncation_length = 10
truncate_to_repo = false

[git_status]
conflicted = "💥"
ahead = "🏎💨"
behind = "🥲"
diverged = "😵"
untracked = "🌚"
stashed = "📦"
modified = "📝"
staged = '🔦'
renamed = "🏷"
deleted = "🗑"

[[battery.display]]
threshold = 100 // バッテリー残量が常に表示されるように設定
style = "bold blue"

[battery]
full_symbol = "🤗"
charging_symbol = "😌"
discharging_symbol = "😨"

[time]
disabled = false
use_12hr = true // 12時間表示に設定

[memory_usage]
disabled = false
threshold = -1 // 常にメモリ使用率が表示されるように設定
style = "bold dimmed green"
